# test_assignee.py
import json

# Sample enriched bug report data as a JSON object
# (This would normally be generated by GPT, but we're hardcoding it here for testing.)
sample_enriched_data = {
    "title": "Feature Request: Gambling Savings Account",
    "priority": "High",
    "recommended_assignee": "kp07usa",
    "labels": ["Feature"],
    "attachments": []
}

# Updated assignee mapping based on your query output
ASSIGNEE_MAP = {
    "kp07usa": "4c6b43ac-b384-42eb-8715-cfa156f58400",
    "tut50103": "a788f89f-f3cd-4a56-8194-b2986a91f306"
}

def get_assignee_id(enriched_data):
    # Extract the recommended assignee (convert to lower-case for mapping)
    recommended = enriched_data.get("recommended_assignee", "").strip().lower()
    return ASSIGNEE_MAP.get(recommended, None)

if __name__ == "__main__":
    assignee_id = get_assignee_id(sample_enriched_data)
    print("Enriched Data:")
    print(json.dumps(sample_enriched_data, indent=2))
    print("\nMapped Assignee ID:", assignee_id)